// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"dining_home_backend_newest/service/main/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.GlobalMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/viewscoreboard",
					Handler: ViewScoreboardHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.GlobalMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/bond",
					Handler: BondHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.GlobalMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/updatestatus",
					Handler: UpdateStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/messagereceived",
					Handler: MessageReceivedHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/joingroup",
					Handler: JoinGroupHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)
}
